# Generated by Django 2.2.5 on 2019-10-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.CharField(default=1, max_length=2, verbose_name='Age'),
            preserve_default=False,
        ),
    ]
