# Generated by Django 2.2.5 on 2019-10-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delete_date',
            field=models.DateField(auto_now_add=True, default='', verbose_name='Delete date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modify_date',
            field=models.DateField(auto_now_add=True, default='', verbose_name='Modify date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
