# Generated by Django 2.2.5 on 2019-10-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='delete_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modify_date',
        ),
    ]
