# Generated by Django 2.2.5 on 2019-10-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191001_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
